spring.application.name=ai-inquiry-system

spring.datasource.url=jdbc:sqlserver://localhost;instanceName=SQLEXPRESS01;databaseName=AI_Inquiry_System;encrypt=true;trustServerCertificate=true;integratedSecurity=true
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver